### ISSUE TITLE
osx

### ISSUE THREAD

**Issue by joeblew99** [nigeltao/taowm#2]
osx does not support xsession from what i have found googling around.
Any ideas ? Would like to try this out and see how it feels. Its a good idea.

Do you use this when developing ?

**Comment by nigeltao** [comment]
I use taowm every day, but only on Linux. I don't use OS X with any regularity.

I'm open to a proof by example that I'm wrong, but I doubt it's feasible to run an X11 window manager on OS X in any practical sense. I don't have any ideas if you'd like to try, so I'm going to close this as infeasible for now.

**Comment by joeblew99** [comment]
Ok cheers. Just wanted to check

**Comment by joeblew99** [comment]
Can I ask about shiny ? I have been watching it for a bit, and I needing a pure golang GUI for desktops. It's for 2D CAD type software. 
At the moment I am using Google flutter, and it works, but its not golang. Flutter is Dart based.

So is shiny at least runnable ? I might be able to port the gxui GUI controls across to it ?

**Comment by nigeltao** [comment]
Shiny is runnable, but it's at a very early stage right now. In any case, let's discuss shiny on the golang-nuts mailing list, and not in the taowm bugtracker. :-)

**Comment by joeblew99** [comment]
Ok goog idea. I really hope your project gets more contributed. Flutter is
my only option, but I want golang to get a pipelined UI lib
